import React from 'react';
import { ArrowLeft, Network, Zap, Cpu, GitMerge, Sparkles, Activity, ChevronRight } from 'lucide-react';

interface AlgorithmsPageProps {
  onBack: () => void;
}

const AlgoCard: React.FC<{
  title: string;
  subtitle: string;
  icon: React.ReactNode;
  color: string;
  description: string;
  pros: string[];
  cons: string[];
  formula?: string;
}> = ({ title, subtitle, icon, color, description, pros, cons, formula }) => (
  <div className="group relative bg-slate-900/60 backdrop-blur-md border border-slate-800 rounded-2xl p-8 overflow-hidden hover:border-slate-600 transition-all duration-500">
    <div className={`absolute inset-0 opacity-0 group-hover:opacity-5 transition-opacity duration-500 bg-gradient-to-br ${color} to-transparent`} />
    
    <div className="relative z-10 grid grid-cols-1 lg:grid-cols-3 gap-8">
      {/* Header & Icon */}
      <div className="lg:col-span-1 flex flex-col gap-4">
        <div className={`w-14 h-14 rounded-2xl bg-slate-800 border border-slate-700 flex items-center justify-center text-white shadow-xl group-hover:scale-110 transition-transform duration-500`}>
          {icon}
        </div>
        <div>
          <h3 className="text-2xl font-bold text-white mb-1">{title}</h3>
          <p className={`font-mono text-xs uppercase tracking-wider font-bold text-transparent bg-clip-text bg-gradient-to-r ${color} to-slate-400`}>
            {subtitle}
          </p>
        </div>
      </div>

      {/* Content */}
      <div className="lg:col-span-2 flex flex-col gap-6">
        <p className="text-slate-400 leading-relaxed text-sm border-l-2 border-slate-800 pl-4">
          {description}
        </p>

        {formula && (
            <div className="bg-slate-950/50 rounded-lg p-3 font-mono text-[10px] text-slate-500 border border-slate-800/50">
                <span className="text-slate-600 select-none">$ </span>{formula}
            </div>
        )}

        <div className="grid grid-cols-2 gap-4 mt-auto">
          <div>
            <span className="text-[10px] uppercase font-bold text-emerald-500 mb-2 block">Advantages</span>
            <ul className="space-y-1">
              {pros.map((p, i) => (
                <li key={i} className="text-xs text-slate-400 flex items-start gap-2">
                  <span className="w-1 h-1 rounded-full bg-emerald-500/50 mt-1.5" />
                  {p}
                </li>
              ))}
            </ul>
          </div>
          <div>
            <span className="text-[10px] uppercase font-bold text-red-500 mb-2 block">Limitations</span>
             <ul className="space-y-1">
              {cons.map((c, i) => (
                <li key={i} className="text-xs text-slate-400 flex items-start gap-2">
                  <span className="w-1 h-1 rounded-full bg-red-500/50 mt-1.5" />
                  {c}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
);

const AlgorithmsPage: React.FC<AlgorithmsPageProps> = ({ onBack }) => {
  return (
    <div className="h-full bg-slate-950 relative text-slate-200 selection:bg-blue-500/30 overflow-y-auto">
        
      {/* Background Elements (Fixed so they stay put while scrolling) */}
      <div className="fixed top-0 left-0 w-full h-96 bg-blue-900/10 blur-[120px] rounded-full pointer-events-none" />
      <div className="fixed inset-0 opacity-[0.03] pointer-events-none"
        style={{
            backgroundImage: `linear-gradient(#fff 1px, transparent 1px), linear-gradient(90deg, #fff 1px, transparent 1px)`,
            backgroundSize: '40px 40px'
        }}
      />

      <div className="relative z-10 max-w-6xl mx-auto px-6 py-12">
        
        {/* Header */}
        <div className="flex items-center gap-4 mb-16">
            <button 
                onClick={onBack}
                className="p-3 rounded-full bg-slate-900 border border-slate-800 text-slate-400 hover:text-white hover:border-slate-600 transition-all group"
            >
                <ArrowLeft size={20} className="group-hover:-translate-x-1 transition-transform" />
            </button>
            <div>
                <h1 className="text-3xl md:text-4xl font-bold text-white tracking-tight">Optimization Engines</h1>
                <p className="text-slate-500 text-sm font-mono mt-1 flex items-center gap-2">
                    <Activity size={12} /> Technical Documentation
                </p>
            </div>
        </div>

        {/* Grid */}
        <div className="grid grid-cols-1 gap-8 pb-20">

            <AlgoCard 
                title="Centerline"
                subtitle="Geometric Baseline"
                icon={<Activity size={28} />}
                color="from-slate-500"
                description="The foundational path generated by calculating the midpoint between left (blue) and right (yellow) cones. It uses a greedy nearest-neighbor search with directional biasing to connect discrete cones into a continuous loop."
                pros={["Zero computational cost", "Robust reference for constraints", "Safe middle ground"]}
                cons={["Not time-optimal", "Ignores corner apexing", "High curvature inputs"]}
                formula="P_i = (Blue_i + Yellow_i) / 2"
            />

            <AlgoCard 
                title="Laplacian Smoothing"
                subtitle="Elastic Band Method"
                icon={<Zap size={28} />}
                color="from-purple-600"
                description="An iterative smoothing algorithm that treats the path like a stretched rubber band. Each point moves towards the average position of its neighbors while being constrained within the track boundaries."
                pros={["Extremely fast (real-time)", "Removes jitter/noise", "Creates organic flow"]}
                cons={["Cuts corners aggressively", "Does not consider physics", "Can get stuck in local minima"]}
                formula="P_new = P_i + \lambda * (Avg(Neighbors) - P_i)"
            />

            <AlgoCard 
                title="RRT* Stochastic"
                subtitle="Rapidly-exploring Random Tree"
                icon={<Network size={28} />}
                color="from-emerald-500"
                description="A probabilistic algorithm that randomly samples the drivable surface to find shortcuts. RRT* rewires the path connectivity to asymptotically approach the optimal shortest path through the track."
                pros={["Finds global shortcuts", "Explores complex topologies", "Escapes local minima"]}
                cons={["Jagged/Non-smooth output", "High variance between runs", "Computationally expensive"]}
                formula="Cost(x_new) = Cost(x_nearest) + Dist(x_nearest, x_new)"
            />

            <AlgoCard 
                title="QP / Minimum Curvature"
                subtitle="Quadratic Programming"
                icon={<Cpu size={28} />}
                color="from-orange-500"
                description="Solves a convex optimization problem to minimize the path's curvature (2nd derivative) subject to track width constraints. This simulates the 'racing line' taken by professional drivers to maximize corner exit speed."
                pros={["Physically optimal arcs", "Maximizes minimum velocity", "Smooth steering inputs"]}
                cons={["Requires good initial guess", "Can oscillate on straightaways", "Iterative solver needed"]}
                formula="Minimize \Sigma || P_{i-1} - 2P_i + P_{i+1} ||^2"
            />

            <AlgoCard 
                title="Hybrid Blend"
                subtitle="QP + Laplacian"
                icon={<GitMerge size={28} />}
                color="from-cyan-500"
                description="Combines the shortest-path characteristics of Laplacian smoothing with the curvature minimization of QP. This allows tuning the trade-off between distance traveled and cornering speed."
                pros={["Balanced trajectory", "Tunable aggression", "Robust convergence"]}
                cons={["Compromise solution", "Not strictly optimal in either domain"]}
                formula="Target = (1-w)*Laplacian + w*QP"
            />

            <AlgoCard 
                title="RRT* + QP Pipeline"
                subtitle="Global Search + Local Optimization"
                icon={<Sparkles size={28} />}
                color="from-pink-500"
                description="The ultimate pipeline. First, RRT* explores the track to find the best topological shortcuts (the 'strategy'). Then, the QP solver polishes this rough path into a smooth, drivable racing line (the 'technique')."
                pros={["Best possible lap times", "Intelligent apex selection", "Physically realizable"]}
                cons={["Most CPU intensive", "Complex implementation"]}
                formula="Path = QP_Smooth( RRT_Star( Centerline ) )"
            />

        </div>

        {/* Footer CTA */}
        <div className="border-t border-slate-800 pt-10 flex justify-between items-center">
            <span className="text-slate-500 text-xs font-mono">Path Planning Studio Documentation</span>
            <button onClick={onBack} className="text-sm font-bold text-blue-400 flex items-center gap-2 hover:text-blue-300 transition-colors">
                Back to Simulator <ChevronRight size={16} />
            </button>
        </div>

      </div>
    </div>
  );
};

export default AlgorithmsPage;